Django_pjt_01/django_pjt/movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'), # 전체 영화 목록 페이지 조회
    path('new/', views.new, name='new'),  # 새로운 영화 생성 페이지 조회
    path('create/', views.create, name='create'),  # 단일 영화 데이터 저장
    path('<movie_id>/', views.detail, name='detail'),  # 단일 영화 상세 페이지 조회 
    path('<movie_id>/edit/', views.edit, name='edit'),  # 기존 영화 수정 페이지 조회
    path('<movie_id>/update/', views.update, name='update'),  # 단일 영화 데이터 수정
    path('<movie_id>/delete/', views.delete, name='delete'),  # 단일 영화 데이터 삭제
]

Django_pjt_01/django_pjt/mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
]

Django_pjt_01/django_pjt/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)  # 영화 제목
    audience = models.IntegerField()         # 관객 수
    release_date = models.DateField()        # 개봉일
    genre = models.CharField(max_length=30)  # 장르
    score = models.FloatField()              # 평점
    poster_url = models.TextField()          # 포스터 경로
    description = models.TextField()         # 줄거리

    def __str__(self):
        return self.title

Django_pjt_01/django_pjt/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie

# 1) 전체 영화 데이터 조회 및 index.html 렌더링
def index(request):
    movies = Movie.objects.all()
    context = {
        'movies': movies,
    }
    return render(request, 'movies/index.html', context)


# 2) 장르 데이터 제공 및 new.html 렌더링
def new(request) :
    return render(request, 'movies/new.html')


# 3) 새로운 영화 데이터 저장 및 detail 페이지로 리다이렉트
def create(request):
    title = request.POST.get('title')
    audience = request.POST.get('audience')
    release_date = request.POST.get('release_date')
    genre = request.POST.get('genre')
    score = request.POST.get('score')
    poster_url = request.POST.get('poster_url')
    description = request.POST.get('description')

    movie = Movie()
    movie.title = title
    movie.audience = audience
    movie.release_date = release_date
    movie.genre = genre
    movie.score = score
    movie.poster_url = poster_url
    movie.description = description
    movie.save()

    return redirect('movies:detail', movie.pk)


# 4) 단일 영화 데이터 조회 및 detail.html 렌더링
def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)

    context = {
        'movie': movie,
    }
    return render(request, 'movies/detail.html', context)


# 5) 수정 대상 영화 데이터 조회 및 edit.html 렌더링
def edit(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    context = {
        'movie': movie,
    }
    return render(request, 'movies/edit.html', context)


# 6) 영화 데이터 수정 및 detail 페이지로 리다이렉트
def update(request, movie_id):
    movie = Movie.objects.get(pk=movie_id)
    
    movie.title = request.POST.get('title')
    movie.audience = request.POST.get('audience')
    movie.release_date = request.POST.get('release_date')
    movie.genre = request.POST.get('genre')
    movie.score = request.POST.get('score')
    movie.poster_url = request.POST.get('poster_url')
    movie.description = request.POST.get('description')
    movie.save()

    return redirect('movies:detail', movie.pk)


# 7) 단일 영화 데이터 삭제 및 index 페이지로 리다이렉트
def delete(request, movie_id):
    if request.method == 'POST':
        movie = Movie.objects.get(pk=movie_id)
        movie.delete()
    return redirect('movies:index')

Django_pjt_01/django_pjt/movies/templates/movies/detail.html
{% extends 'base.html' %}
{% block content %}
<h1>DETAIL</h1>
<hr>
<img src="{{ movie.poster_url }}" alt="영화 포스터" width="500">
<br><br>
<p>{{ movie.title }}</p>
<p>Audience : {{ movie.audience }}</p>
<p>Release Dates : {{ movie.release_date }}</p>
<p>Genre : {{ movie.genre }}</p>
<p>Score : {{ movie.score }}</p>
<p>{{ movie.description }}</p>
<a href="{% url 'movies:edit' movie.pk %}">EDIT</a>
<form action="{% url 'movies:delete' movie.pk %}" method="POST">
    {% csrf_token %}
    <button>DELETE</button>
</form>
<a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}

Django_pjt_01/django_pjt/movies/templates/movies/edit.html
{% extends 'base.html' %}
{% block content %}
<br>
<h1>EDIT</h1>
<hr>
<form action="{% url 'movies:update' movie.pk %}" method="POST">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" id="title" name="title" value="{{ movie.title }}">
    <br>
    <label for="audience">AUDIENCE</label>
    <input type="number" id="audience" name="audience" value="{{ movie.audience }}">
    <br>
    <label for="release_date">RELEASE_DATE</label>
    <input type="date" id="release_date" name="release_date" value="{{ movie.release_date | date:'Y-m-d' }}">
    <br>
    <label for="genre">GENRE</label>
    <select name="genre" id="genre" value="{{ movie.genre }}">
        <option value="comedy">코미디</option>
        <option value="romance">로맨스</option>
        <option value="action">액션</option>
        <option value="drama">드라마</option>
        <option value="horror">공포</option>
    </select>
    <br>
    <label for="score">SCORE</label>
    <input type="number" id="score" name="score" min="0" max="5" value="{{ movie.score }}">
    <br>
    <label for="poster_url">POSTER_URL</label>
    <input type="url" id="poster_url" name="poster_url" value="{{ movie.poster_url }}">
    <br>
    <label for="description">DESCRIPTION</label>
    <textarea name="description" id="description" cols="30" rows="10">{{ movie.description }}</textarea>
    <br>
    <input type="reset" value="Reset">
    <button>Submit</button>
</form>
<hr>
<a href="{% url 'movies:index' %}">BACK</a>
{% endblock content %}

Django_pjt_01/django_pjt/movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}
<h1>INDEX</h1>
<br>
<a href="{% url 'movies:new' %}">[NEW]</a>
<hr>
{% for movie in movies %}
<p>
    <a href="{% url 'movies:detail' movie.pk %}">{{ movie.title }}</a>
    {{ movie.score }}
    <hr>
</p>
{% endfor %}
{% endblock content %}

Django_pjt_01/django_pjt/movies/templates/movies/new.html
{% extends 'base.html' %}
{% block content %}
<h1>NEW</h1>
<hr>
<form action="{% url 'movies:create' %}" method="POST">
    {% csrf_token %}
    <label for="title">TITLE</label>
    <input type="text" id="title" name="title">
    <br>
    <label for="audience">AUDIENCE</label>
    <input type="number" id="audience" name="audience">
    <br>
    <label for="release_date">RELEASE_DATE</label>
    <input type="date" id="release_date" name="release_date">
    <br>
    <label for="genre">GENRE</label>
    <select name="genre" id="genre">
        <option value="comedy" selected>코미디</option>
        <option value="romance">로맨스</option>
        <option value="action">액션</option>
        <option value="drama">드라마</option>
        <option value="horror">공포</option>
    </select>
    <br>
    <label for="score">SCORE</label>
    <input type="number" id="score" name="score" min="0" max="5">
    <br>
    <label for="poster_url">POSTER_URL</label>
    <input type="url" id="poster_url" name="poster_url">
    <br>
    <label for="description">DESCRIPTION</label>
    <textarea name="description" id="description" cols="30" rows="10"></textarea>
    <br>
    <button>Submit</button>
</form>
<hr>
<a href="{% url 'movies:index' %}">BACK</a>

{% endblock content %}

Django_pjt_01/django_pjt/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<body>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
</body>
</html>